### ISSUE TITLE
spira-testng Listener not working with Java 11 due to missing imports

### ISSUE THREAD

**Issue by weendigo** [Inflectra/spira-testng#1]
I am not able to use the Spira TestNG listener with Java 11.
A bunch of imports is not available anymore: 
![image](https://user-images.githubusercontent.com/5716977/67893253-8645ee80-fb56-11e9-8da9-eaf15877252f.png)

Namely these:
javax.jws.*
javax.xml.ws.*

Apparently, package javax.jws is in module java.xml.ws in Java 9+, and that module is not enabled by default. It has been removed entirely in Java 11.

**Comment by weendigo** [comment]
Solved by adding following dependencies in POM.xml:

		
		<dependency>
		    <groupId>javax.xml.ws</groupId>
		    <artifactId>jaxws-api</artifactId>
		    <version>2.3.1</version>
		</dependency>
		
		
		<dependency>
		    <groupId>org.glassfish.main.javaee-api</groupId>
		    <artifactId>javax.jws</artifactId>
		    <version>3.1.2.2</version>
		</dependency>

**Comment by simonhbor** [comment]
Thanks for the feedback. We will add this to the pom for the next release
