### ISSUE TITLE
DataProviders Vs Spira Annotation

### ISSUE THREAD

**Issue by Tonicku** [Inflectra/spira-testng#5]
Would you mind to provide a solution how to use Spira Annotation with DataProviders ? how to keep the mapping Spira - Test DataEntry ?

**Comment by simonhbor** [comment]
Please take a look at our online documentation here: http://spiradoc.inflectra.com/Unit-Testing-Integration/Integrating-with-TestNG/
If you need any further help and are an Inflectra customer please email us at support@inflectra.com

**Comment by Tonicku** [comment]
Hi yipmarvel, the documentation doesn't speak at all about DataProviders. That is my question. Is there a way to use Spira Annotation with DataProviders ?
Thank for re opening the ticket
